apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  mountOptions:
    - uid=33
    - gid=33
    - file_mode=0755
    - dir_mode=0755
  resources:
    requests:
      storage: 5Gi
