apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-drupal-adminuser-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:UfcvW10j5bc=,iv:DJ9/eETRR8qPjuzVUf49n9i8Jd3Z/eMudXYxjyV0wI0=,tag:sxMUJvQfI6fv4Q4zyvkZCQ==,type:str]
    password: ENC[AES256_GCM,data:39koxL5Eu/7kLkUyMvbLkPLapYQ=,iv:J78afBzSwBN7QRYM90V427sgHNmPAa7SUb66kzHpzqM=,tag:H/LOvvr7k+7sNgAx1qyOHw==,type:str]
sops:
    lastmodified: "2026-02-05T12:37:44Z"
    mac: ENC[AES256_GCM,data:eUoF4kO8ZW6Kj2sl83ZOP0/Sf87LFcSFI0NfSpUhKMq6diGlaaB3z+13V9ZuiL/+pfxKKfRnIBjECB3NJWLBpbjNuiM4c/1xr2kBehqiBrjvoGHwhcA6nIHLZnxRNIWZRThH700WAqz43PAUdKc2PFE2V4FM3s+zfQj/Uw89MxY=,iv:pgBgKlyY3GYJjXPlLl2PNxkYE0NVTYzof9hC9UmUDZk=,tag:tUw3b3THgJfguHlqqvmTqA==,type:str]
    pgp:
        - created_at: "2026-02-05T12:37:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAxey49n0t1DvUPrLbcH1H3PpPnHO2dRA1jz56M7oZ1h0w
            4OkW1gbyOET38aS/KLmf+xp5MeX3mmZbdeBYJcKkDEeORdTwhJSSuJT/rx+FtWrv
            1GYBCQIQZkhqKgSp1t2q0iM7J45WevGupf9FgZ1JeamUJPTEveb9pRi9yNAjaRaj
            fwe7VCXlyiBTAYz315miHYxmIyqDgsm81mqam7+5NHRC5oblyLOwnEUX2y2SSen3
            e2RLS0/nsD0=
            =6oRa
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1