apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-drupal-iknowbase-graphql-studiekatalog-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nJrK23fSS1Npkn4evOdGzQ==,iv:Fzj7j1C3/XogAKVFdiVW5Dv1ZKpW1A1s0MuJrx/5OjI=,tag:kK6oNOtpfWTZYNFOUAOGrg==,type:str]
    password: ENC[AES256_GCM,data:G5ipBbxcQ3sJ+7q2DyqbgGOPLElBMBel6lCpu/ReAswRU2RM,iv:/O5KIrSjPIcwfAK3nytkHAfQ/kAlS7xEg8WRCTMY2nE=,tag:u7J++UT8u/RZvP+vZA2rMA==,type:str]
sops:
    lastmodified: "2026-02-05T12:24:28Z"
    mac: ENC[AES256_GCM,data:bo1N8wYp4WDjSd4ymGyTXkk8h5Wul/A5ttGZZsCFBI9Ccz6Phu3eZznT53h8+TZL3FCXJOJjopDfRbo2Rt3BpY8dY5QAGGbUhaUB0zMBNd3eL0mQ+kfItjYeWM3YHvnSZVobqCSGMo4Tx+MoyIlv/9LAfRR5gun3klZtGS+qESU=,iv:8uBUlpP7kzNsAb9/QSwO3V3RnRbdqamySEHvgGRLJJw=,tag:238gYzASKcF1WmdwRKFX9A==,type:str]
    pgp:
        - created_at: "2026-02-05T12:24:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAViYdZMSinR8pqxjSh8Ptzskys7J6P42pk6PXuY8WKXow
            QV/dHpQBzmvS1w8cLvGupK8NFGPwZem2k6yOiZQG173va8e6rPCFDNq+2CYyM4il
            1GgBCQIQzq0dyn6OgnH0pQsSywjVrygCZOxlLOljKCfUzUAjIFwKIyexsfW2GvlS
            JQPPH7v7rjvzSwJAZ/Fegywzz1QxY+uPT4Rdm44Ck6RlYeXka0pMKoaHwsgSZxKK
            6ZIwHXkqV9e86g==
            =rAMk
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1