apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - image-repository.yaml
components:
  - ../../components/postgres-database
  - ../../components/image-update
patches:
  - path: patches/nginx-image.yaml
  - path: patches/drupal-image.yaml