apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ${app_name}
spec:
  imageRepositoryRef:
    name: ${app_name}
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  policy:
    semver:
      range: '>=0.0.0'
