apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: ${app_name}
spec:
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@noreply.uib.no
      messageTemplate: '{{ .AutomationObject }}: {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: uit-it-webadm
    namespace: uit-it-webadm
  update:
    strategy: Setters
    path: base/drupal