apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-db-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cWZ8MJP6G701h6Xe,iv:vfWSSZoy6Vq0J+5H4ZE7PY+ROQ/HD0qA9XUMJ+Yrccg=,tag:ihBYluo2lItVacGfIF6iDA==,type:str]
    password: ENC[AES256_GCM,data:cKf0/C708/LhHJi3b6SHDuFmDCcL,iv:0RIKQd4dQiBIuYj8fdJI7aJX9qdu4tSm7ZhsoiWGXFM=,tag:ci3kP3PoypvnvTJ588Zm8w==,type:str]
sops:
    lastmodified: "2026-04-24T09:25:48Z"
    mac: ENC[AES256_GCM,data:aV611k/8MtUGJZ4PAZfE4bJ+rg7w/N96KqV4yVQUPNSsqAB0LE+wOlxv6P3flon1fUHYO3bXErx9jxPAiNoYwh04avqbamIt/j5RthvgbEmS1c0YOd9y++WCEbjN846BwF9qtInaW2DQoELw96gPBcGwGlqTePGErF2G93ydpq8=,iv:UHOGOXeOl84Dy0h53rK0RZp5OUHXSIkkIf78RMS8U4c=,tag:xrfIEtYnyvSHsUsq/DMFaw==,type:str]
    pgp:
        - created_at: "2026-04-24T09:25:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAZjMCeCx1ugS/Gc1iIlt5ZjoWtwJ24B0dJbI0puBXXlgw
            9739xr7uWb1QXISb0cLZGkhGmAIh1JqaQHVhqqiksRaakgocB3xwzgfmezdk25Z1
            1GgBCQIQ58S90u6ZfP3YQ8uQldnhaVNUYqczGqIyLH+o3M+4n3AX8yWjFZwS9APu
            rhp91AqPNwf7CXPHYJbOzfG4y92pGbeaGaKPZbGIgO7Kt8fjpWaF5+aEX1pwTRnT
            s0jY6Q/MwZPnqQ==
            =vBuY
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1