apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PCHz/PH9EVB6m3scwDg99kfZLw1TDyJlPJvgGXXUrEqL1KAUEIPyLfSSxn6xQWY4odmprOKzqcVABXUwlXJcTYla0lIU+SJeeUcSo+IHmDKPY5my/EL+pFPwujF+uWmmMdAYSVvTavjqViSSJEgAFJWladkmibi7q8t/4yFX7zVJEI63H53oEYaZfEQ8J/6xq7KaSs5XP4tEbRrKP1ZC3DGRQg9Kq+wDrkmUWC/kL5VxLvtzRUFIP6h3bM6NZULfTNL50Vll4FbOPB79mP7dQrJSja5ixfZcbHJoM7nPaJLs3DgVnVtElplat0cW7s+CxjkGmL6pQsHejnfANjfAatRQzqnv/7bLi5vjm95XzEJGSsm5B0Mr1A6+7aNpFJtyhmmEw20z39L363WQuwEtV02Uyyc485f1k4fXVw==,iv:oeGwDzZYPBNM+LtqXZJVh0CbSLI05KnIeevTn8dQ1sE=,tag:eXIvuXYVQQvRQLNLEN9BNw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: uitcontainerregistry
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2026-01-26T12:56:12Z"
    mac: ENC[AES256_GCM,data:5v7USQCALA1NxX0OHW2i05xOst5G/+ELZIg4MD2SlsTZTZMXxdvL3vMcovDRkbL0tCFI/heBdCxkKfo+qiuYE9PpCUv3egKMIGgMnIiN4Zw+NPH/dfmGlqrK3EXRA5EHmyzSU5LRPH4ADGNVkjUbUo75u7B7c6wZrwZR6p5YDIk=,iv:Sdhm4eowOxhyUWDiNSFuhXA54pspNNSvjSJQEtme05w=,tag:yOSZTVD5ItEXYtawhtf/NQ==,type:str]
    pgp:
        - created_at: "2026-01-26T12:56:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAVBI+qtBwjWSKxnLWnmMyQh0B2YeZIXgDEG5BzLei7gQw
            ybruQ962VSYbYteJ0QLGcZk4tQDWyxKYZT+JKQFiKw9y9eudpAif769Pd26X9HfU
            1GgBCQIQNKyI07n4i+H8r7sKfhWunw6rII0tMppVaUsrdm0LOler97LbK9dOjCr7
            AjYi/vBSaRzykmfaYzuQQda7Is02nKhA6k6npy4CsHCzRp0h/scO8DSPQT87IJyE
            3DgIm1rX2pH7zA==
            =W0Rw
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1