apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - ingress.yaml
configMapGenerator:
- name: nginx-config
  files:
  - default.conf=nginx.conf