apiVersion: batch/v1
kind: Job
metadata:
  name: ${app_name}-drupal-deploy-job
spec:
  backoffLimit: 0
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: ${app_name}-drupal-deploy-job
          image: PATCH_ME
          command:
            - /bin/sh
            - -c
            - "drush deploy"
          ports:
            - name: fastcgi
              containerPort: 9000
          volumeMounts:
            - name: phpfpm-config
              mountPath: /usr/local/etc/php-fpm.d/zz-docker.conf
              subPath: zz-docker.conf
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/99-drupal.ini
              subPath: 99-drupal.ini
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
          # Prevent escalation attacks
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: phpfpm-config
          configMap:
            name: phpfpm-config-post-deploy
        - name: php-config
          configMap:
            name: php-config-post-deploy
      restartPolicy: Never
