apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-secret-dbdump-blob
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kJjnO6lP,iv:m/4PCsXlVk7hN0QDJKpyjaBiK1/Hv0BsDYpVzUaujRY=,tag:HMIe5R9CgcqjsMbf9m0eSw==,type:str]
    password: ENC[AES256_GCM,data:kq0fsWkTqi2coWW2Zzx2J3jsa5Wbk8jQKqBrrcMz9MYiheHY8iapeiQeg9zmVMYb,iv:V4y3Ps9RFGNPDbQq3SjllDDe5aNyQw9kHR3G56jwTNk=,tag:RiJfyJj4vjYKft73adbvDQ==,type:str]
sops:
    lastmodified: "2026-06-07T14:37:06Z"
    mac: ENC[AES256_GCM,data:mVeIe/Ebup75E5W6Zs9PYwWfqIfk9wSXqgPtegrah9iWh55g210o6eKNAug4fq2kqjE8dtTEetb7IoR1gUsk5debTw5PPpKKOUJE8J6Xh0JkBo6+GM+jRVk/3Fb2Ol3rwyHHLet7KYsVwJDnNhWxFZdOA2bh2FUyzzvS1oCNjvw=,iv:PxXGreRAx9u/M+D/0TU4KSscfSA4qeWIHJXwp33cZzc=,tag:Ih2R4s6s77nR/nlI1efY3w==,type:str]
    pgp:
        - created_at: "2026-06-07T14:37:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAfPqTEfnefOCMTZtg6+GiaEIj4hf98xYl8nnsVnkdzlAw
            JB4oaHsPXG3ICQyXGRewG9Ss+GPxhwHgHJRlmSWB4m94pZzsT5SIarYNiJytEvvQ
            1GgBCQIQeojxOuFgE/HukZ4K6HueL5cca/WpTAGyJ2297ZGppE8bnSZWaaYr/EKq
            pNujHpc9FiwzYh+1mwusCOP4URJudlHKAxG4JOL4av3YZNE6kD25FaKMVijV8orE
            p6eRThJ2kivClw==
            =g1ej
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1