apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-secret-dbdump-blob
type: kubernetes.io/basic-auth
stringData:
    db-export-blob-storage-secret: ENC[AES256_GCM,data:m+T+6MNatFnCPqrkIfE1S5h/PgauFr6viF25UwgwlSyvD75HHo4r23qEjYQkqExKfyM=,iv:pqRd/qYAb1uDUleWcQv2d4T33AAnwNoIvnaa0A7DVNU=,tag:ieJEF/sZOtEu0hceM/Redw==,type:str]
sops:
    lastmodified: "2026-06-07T14:04:44Z"
    mac: ENC[AES256_GCM,data:0ypYI51Ngs/QKAC1i2t0MXc42wM7ZBrgIQT5lxLdAXivT27qvpHHhpI6HFZidRvxCZ8v1sQtfEF/wU/gwoCc6I2DLDlmwkIaxO/VkNbk3RH9DiBgcWiiF917t6NpbCiWqoEIOxsFz74EFNVXtvNkfUo5QWurWfEzl6n0KNo7X6w=,iv:aV5jjFjTma6zpzsVtQZ7UAcztrNzKTCR9EOsEZJWErg=,tag:wDBurf7VCJzmifrtHof5dg==,type:str]
    pgp:
        - created_at: "2026-06-07T14:04:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdA1bQMWbreOwhTQyr5YOBej7MSSXMADEZDLzNLUj66ajsw
            bV8RAciwCNuIXqxRc2OOfhylHshyR6TrrXHdAT4897eWcS9tiF0K4UjVQBTMNcmh
            1GgBCQIQUpfKPo3Mdj8SeZGUglyLK662jKnXEu9TILERajb6gali2rw5023ByOjC
            1AFQm2D6U8UkH8o5n7AACV+2G+TEOCEWndvpSYcfShQIODOqm1Ca8a6ZP+Bxr/9y
            RlDS35jdDiqO2A==
            =nS3c
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1