apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-openai-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:kGpTmVDEbxlX/RFY0nepXkEvveUT3rxcgOWK1Ki5f7s75UvXw0ZmugQgw0e+d6ud13i4bAQu0FW8l2CpN7eH59q8kGev7oc75/ynZOXxdP/vEFw0,iv:2vJuGFu2Qb9MgYyXG/KbAWJAPBeSRq/jgSZ3Sq0r+wU=,tag:eTXAj9PbWv13tA7z9he47g==,type:str]
    username: ENC[AES256_GCM,data:sG8SRVeadK37UA==,iv:Lxs32sxUugViZsxvh+jqv1q4lJXGVH61qPWXfdytSkg=,tag:etit2ob/zE+g8wUMEdfEsw==,type:str]
sops:
    lastmodified: "2026-07-01T10:57:17Z"
    mac: ENC[AES256_GCM,data:XBlY0cS9qr4saCOmfAXisWI1A7gOxnzDWlTglczkvP00lIuJoycckvl/x/s72z/DRN4O86zUjpxmjmIdlDazPzN9ptovmmZohjuDLE2GdZn7RByLSR4WRmlqJiB0VusOukrRVfRapxk+P9MwcwWnDvBKVHXEVHpSb0FgX8T+iWw=,iv:oUFdu3w75CuQyWNLjTMCQM5JFsQJtubOdho3p1taB4Q=,tag:l8nYC+eOomyFnj/SbP/2Tw==,type:str]
    pgp:
        - created_at: "2026-07-01T10:57:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAkaNtvi97rJwJy3LSblrV2gTCWW1RK/pBwKqu3w6mmEMw
            qcTeNw4d5/zIJopV6vRBWdI346hbpDDa7r+awmIRB7IiNm4EclM4ThM0Oq5vEfYC
            1GgBCQIQqHDICTHZ015G4jwhbM7ndVUPOo6lkzPry0CpUWiADWTTvakh5aYtd15J
            HJ1Qn4HvP4qBU29AufltYyvF1+ViUsEuoa1swKESb1yqRgkUiwXmKJ1NnGKotvC7
            tpoz39ZKoaIVvg==
            =6JtO
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1