apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-db-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:t+Ootw0evH2UPZG1n122UYixW6RL,iv:1lc8OAtunBMPVyZbPnDiyMDw/yKCF73IOlBTeJ922eU=,tag:MOmmO4FVc1a2/6ET5G+/1w==,type:str]
    username: ENC[AES256_GCM,data:riC6n5B1n0O9qqq7mcwwLiU=,iv:TYg2z+vky/Opm+WZLnkNB43GMDUGOHYSH9qCzM17B0U=,tag:pdfUOGi5+QxDEaDS2d1tMQ==,type:str]
sops:
    lastmodified: "2026-06-06T17:59:25Z"
    mac: ENC[AES256_GCM,data:FjxK8s+Dc7S/Oe1ZJ/JYBaLjZOwMoodYiqtoeyljfLc3gB30SSwvOwzMqU6fKTt389h0fdg7HguaYYsMZtOacL0rEFbgDvX1zcKpYr963HTZWyVYh7EPUh4kB8C6DAb/pFIDrGdTtYvucGtr1FHEJMWSq2wmFMIfkrBimAjpiNo=,iv:uPHE1hLF1Cwp/bW3cTufCg2icYQvYm47387mPXMUSCU=,tag:t+jx1LmuxMgWWZUzv6Z/uw==,type:str]
    pgp:
        - created_at: "2026-06-06T17:59:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAZ7ZSVt426bWGr9Rlsz0V/jusJmm5aBNdZ2yKf2z7yyAw
            do+cF5arDN+eSLi9DLhc9p1ok7sa21M+CvvGw2rodu+GmW+G8pvtmsDhFjdQyVth
            1GgBCQIQbe9dRYjDQB1+CGx5lnVokuwYZTo7Lc2ws9xDznQYRj/hWkY6meA6VzG7
            aKQTWcZfoL+eOoq4CM0TqyfVP6BK83na1w5An/YR2mfjscY+JwfT9TvGBpkPwJoq
            Ky1hVFxObDJx+Q==
            =PQ5N
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1