apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-db-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:AxbB6LFPz6f/5XOQ6SiMcBXfCRD4gSCFENmi0CjdKfsigjYJckyM+qOx5XSwf0cwJJj6M0a2lrXQO1TuPGeSlMppNleFObD3PSTDT57QVCmdN72Iccep6nBM7DSeSK0N0gS/cajqJzoiUR1bv98fm6HqbRi+sVieIoNW6/GyLpqTLv+KSucw0LcGC97KaaknNpCM/JMeKmFoOvc25OfSx0UXZIJ4pp64vTjLJOVd/7r9kvS5a7ql69g0IOHG3l47qfW1SAz6BA==,iv:793Qu9csBbQyoOyTDycY5dXBHWpL2eFfx+V4AkAYWcQ=,tag:jJQ7cKS+h4YiaE0c+4l9lw==,type:str]
    username: ENC[AES256_GCM,data:8FhTW+6Gerl0gBraB7868GU=,iv:pf46+ej8KBeD7tyJ7SmXs/92nuwwlW/5ktVes3vMvt8=,tag:QIqjSnzr0gBKNkF7YEf54g==,type:str]
sops:
    lastmodified: "2026-06-06T17:47:01Z"
    mac: ENC[AES256_GCM,data:3SdcwQKvHNTJinOkahv7TrwP2DYt+MCJ7X9pO5B/7Pvs/IAEb8TvMGmo/eEvFIp0Bxx9f6mCqYG3fMJXJ1HDEqhaqb/rFH2cC6B834O5C6Otjk7GiaOnNImiW4bdR6nDAN/WSxmIEQp4QNC59vA8DAeRwOQcGQctZA2g2L2euuk=,iv:zkfJ5NpYVEUI99ALrc1qUcHExhe0g5mPBUG3Czr8ub4=,tag:JT5X+LmrINpFsCjbkh0XBg==,type:str]
    pgp:
        - created_at: "2026-06-06T17:47:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdApbPcTJP8cqDrgFM1DB83ubsO8k8Qxl6vhtyRtppXfGww
            ijZ7gw6X6RXY7yPr3OWSvhnmYLODM2iaItUnn5QAsWPCjbELAyLDAd6Kx8h8XEJP
            1GgBCQIQDYSI/x+8D9c/ycCteezvIBswiFMGTQ+YHD4B1h2dNQm/896TqdW4eyOc
            ynFizeGR0lEEVyWiw4GQWAgWAmAUqO4+hWNTSADkK0op4UGq9vbq0bIiH1pyPhl+
            Lnciz4F0EIQGDg==
            =Y00w
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1