apiVersion: v1
kind: Secret
metadata:
    name: ${app_name}-feide-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:UtTg36k62aC/Z4X0bijTNgPvH/w1Eywy/nBdHP+qfs8+mRsy,iv:CxpEthC8NC1wMoBGRP2DcY7NP12ODGtnTK+DoUe2ykQ=,tag:sTgOHLNKlSSaAC7LCR8Z0w==,type:str]
    username: ENC[AES256_GCM,data:DOaR+/Ug8upbrAJU,iv:Hm+jGUPs5fAviiQMA+TX+HX8N2UMOZ0YCtLJ5Fmy7D0=,tag:Blfr3xQxSJvnM7kIIZ1ErA==,type:str]
sops:
    lastmodified: "2026-10-09T10:43:03Z"
    mac: ENC[AES256_GCM,data:xxQpkMgi2wnw2Q5lsuakdSfiolNfIETrOWUT7/GPnxt7JZaK2Gi14U47dqZBKOtnOEi8vK7Lch1doEbs1gumdiUP32w+Uf42dkhfe+iH8tNpqEL4WPu/ztyDHdMjBUZRYo5OvIyIWT06hc/D6BxEhLRRp8eQt2uVRTxqm7P5UkY=,iv:1XVWGvQU6B3TuBwt+xuBXrrpkEnUQwyTnKN8QK2TDkY=,tag:ihsaNLyDhw90CW3gVMlScA==,type:str]
    pgp:
        - created_at: "2026-10-09T10:43:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNV2Bp8jlH8sSAQdAiZAY/o1ArfVdxvh8m3tmn+wh2lZ9Pkstq26+xoW+n3Mw
            URYGPKXNCsuzvU049LOVEoqx81R+lI6PUb98ZGvCBGtc+q7QHG0dKRPmUsYRl0Qp
            1GgBCQIQPdwaVmJ0an5cmnkCCWpkKBDfe1tutHLyCq1Dq/4VIMmRA4L/4wOpA/Tn
            DDun5dtmMTrUMZwHODy9z7oMmX7t72wFMO3A6oBGBgLCgBKZYk2mi4+tMM/ZrdzL
            HB4soPHFrVh5HQ==
            =FtQL
            -----END PGP MESSAGE-----
          fp: AFDB50935E640B5E952678DCBEE7F92A551628F5
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
