apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${app_name}-files
spec:
  storageClassName: rook-cephfs
  accessModes:
   - ReadWriteMany
  mountOptions:
    - uid=1000
    - gid=1000
    - file_mode=0755
    - dir_mode=0755
  resources:
    requests:
      storage: 7Gi
