apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}-drupal
spec:
  template:
    spec:
      containers:
        - name: ${app_name}-drupal
          image: uitcontainerregistry.azurecr.io/uit/www-drupal:drupal-uib-rails
